# Generated by Django 4.2.20 on 2025-04-30 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='rejection_reason',
        ),
    ]
