# Generated by Django 5.1.6 on 2025-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('bust', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('front', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('arm_length', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('bust_depth', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('bust_distance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('lower_circumference', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('crotch', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
