# Generated by Django 4.0 on 2025-03-03 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WardrobePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('A', 'Package A (₱12,000)'), ('B', 'Package B (₱15,000)'), ('C', 'Package C (₱18,000)')], max_length=1)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refundable_deposit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WardrobePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saritasapp.inventory')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='saritasapp.wardrobepackage')),
            ],
        ),
    ]
