# Generated by Django 4.2.20 on 2025-04-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobepackage',
            name='tier',
            field=models.CharField(blank=True, choices=[('A', 'Package A'), ('B', 'Package B'), ('C', 'Package C')], help_text='Predefined package tier (A, B, C)', max_length=10, null=True),
        ),
    ]
