# Generated by Django 5.1.6 on 2025-03-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Unknown Venue', max_length=255),
            preserve_default=False,
        ),
    ]
