# Generated by Django 4.0 on 2025-04-19 06:26

from django.db import migrations

def populate_itemtypes(apps, schema_editor):
    ItemType = apps.get_model('saritasapp', 'ItemType')
    item_types = [
        ('bridal_gown', 'Bridal Gown'),
        ('groom_tuxedo', 'Groom\'s Tuxedo'),
        ('maid_honor', 'Maid of Honor Dress'),
        ('bestman', 'Bestman Attire'),
        ('bridesmaid', 'Bridesmaid Dress'),
        ('groomsmen', 'Groomsmen Attire'),
        ('flowergirl', 'Flowergirl Dress'),
        ('bearer', 'Bearer Attire'),
        ('mother_gown', 'Mother\'s Gown'),
        ('father_attire', 'Father\'s Attire'),
        ('accessory', 'Wedding Accessory'),
        ('other', 'Other Attire'),
    ]
    for code, name in item_types:
        ItemType.objects.get_or_create(name=code)


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_itemtypes),
    ]
