# Generated by Django 4.2.20 on 2025-05-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='size',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='item',
        ),
        migrations.AddField(
            model_name='size',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saritasapp.color'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saritasapp.material'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saritasapp.style'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='saritasapp.tag'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large'), ('PS', 'Plus Size'), ('KS', 'Kid Size'), ('OS', 'One Size')], max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='InventorySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='saritasapp.inventory')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saritasapp.size')),
            ],
            options={
                'verbose_name': 'Inventory Size',
                'verbose_name_plural': 'Inventory Sizes',
                'unique_together': {('inventory', 'size')},
            },
        ),
        migrations.AddField(
            model_name='rental',
            name='inventory_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='saritasapp.inventorysize'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='inventory_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='saritasapp.inventorysize'),
            preserve_default=False,
        ),
    ]
