# Generated by Django 4.0 on 2025-03-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reservation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
