# Generated by Django 4.2.20 on 2025-05-06 11:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Minimum ₱500 reservation fee', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('500.00'))]),
        ),
    ]
