# Generated by Django 4.0 on 2025-04-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0002_populate_itemtypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={},
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(choices=[('bridal_gown', 'Bridal Gown'), ('groom_tuxedo', "Groom's Tuxedo"), ('maid_of_honor', 'Maid of Honor'), ('bestman', 'Bestman'), ('bridesmaid', 'Bridesmaid'), ('groomsmen', 'Groomsmen'), ('flowergirl', 'Flowergirl'), ('bearer', 'Bearer'), ('mother_gown', "Mother's Gown"), ('father_attire', "Father's Suit or Barong Attire")], max_length=50, unique=True),
        ),
    ]
