# Generated by Django 4.0 on 2025-03-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0002_event_wardrobepackage_wardrobepackageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobepackage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wardrobepackage',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wardrobepackage',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
