# Generated by Django 4.2.20 on 2025-05-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0002_alter_itemtype_options_remove_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorysize',
            options={'ordering': ['size__name'], 'verbose_name': 'Inventory Size', 'verbose_name_plural': 'Inventory Sizes'},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='inventory_decremented',
        ),
    ]
