# Generated by Django 4.2.20 on 2025-04-25 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0002_alter_wardrobepackage_tier'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rental',
            name='saritasapp__created_2d09ca_idx',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.AddField(
            model_name='rental',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(choices=[('bridal_gown', 'Bridal Gown'), ('groom_tuxedo', "Groom's Tuxedo"), ('maid_of_honor', 'Maid of Honor'), ('bestman', 'Bestman'), ('bridesmaid', 'Bridesmaid'), ('groomsmen', 'Groomsmen'), ('flowergirl', 'Flowergirl'), ('bearer', 'Bearer'), ('mother_gown', "Mother's Gown"), ('father_attire', "Father's Suit"), ('other', 'Other')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rented', 'Rented'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
