# Generated by Django 4.0 on 2025-04-13 12:35

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0002_reservation_approved_at_reservation_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='return_after_reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_price',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Flat reservation fee per item', max_digits=8, validators=[django.core.validators.MinValueValidator(500.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated as quantity × reservation price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2025, 4, 13))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 4, 14))]),
        ),
    ]
