# Generated by Django 4.0 on 2025-03-27 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0002_inventory_reservation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Rented', 'Rented'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Rented', max_length=10),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('return_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saritasapp.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saritasapp.inventory')),
            ],
        ),
    ]
