# Generated by Django 4.0 on 2025-04-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0003_alter_itemtype_options_alter_itemtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageRentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returned', models.BooleanField(default=False)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saritasapp.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='WardrobePackageRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start', models.DateField()),
                ('rental_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rented', 'Rented'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_rentals', to='saritasapp.customer')),
                ('customized_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saritasapp.customizedwardrobepackage')),
                ('inventory_items', models.ManyToManyField(through='saritasapp.PackageRentalItem', to='saritasapp.Inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_rentals', to='saritasapp.customerorder')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saritasapp.wardrobepackage')),
            ],
            options={
                'verbose_name': 'Package Rental',
                'verbose_name_plural': 'Package Rentals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='packagerentalitem',
            name='package_rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saritasapp.wardrobepackagerental'),
        ),
        migrations.AlterUniqueTogether(
            name='packagerentalitem',
            unique_together={('package_rental', 'inventory_item')},
        ),
    ]
