# Generated by Django 4.2.20 on 2025-05-05 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0003_alter_inventorysize_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rental', 'verbose_name_plural': 'Rentals'},
        ),
        migrations.AddField(
            model_name='rental',
            name='penalty_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='inventory_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='saritasapp.inventorysize'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['returned_date'], name='saritasapp__returne_32ccb9_idx'),
        ),
    ]
