# Generated by Django 4.2.20 on 2025-04-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0003_remove_rental_saritasapp__created_2d09ca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
