# Generated by Django 4.0 on 2025-04-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0003_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saritasapp.reservation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('rental_approved', 'Rental Approved'), ('rental_rejected', 'Rental Rejected'), ('rental_completed', 'Rental Completed'), ('reservation_approved', 'Reservation Approved'), ('reservation_rejected', 'Reservation Rejected'), ('reservation_completed', 'Reservation Completed')], max_length=30),
        ),
    ]
