# Generated by Django 4.2.20 on 2025-05-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0004_alter_rental_options_rental_penalty_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='pickup_status',
            field=models.CharField(blank=True, choices=[('awaiting_pickup', 'Awaiting Pickup'), ('picked_up', 'Picked Up'), ('no_show', 'No Show')], max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['pickup_status'], name='saritasapp__pickup__254ce2_idx'),
        ),
    ]
