# Generated by Django 4.2.20 on 2025-04-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0004_rental_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobepackagerental',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saritasapp.wardrobepackage'),
        ),
    ]
