# Generated by Django 4.0 on 2025-04-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0004_packagerentalitem_wardrobepackagerental_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagerentalitem',
            options={'verbose_name': 'Rented Package Item', 'verbose_name_plural': 'Rented Package Items'},
        ),
        migrations.AlterModelOptions(
            name='wardrobepackagerental',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='inventory_items',
        ),
        migrations.AddField(
            model_name='packagerentalitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wardrobepackagerental',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wardrobepackagerental',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_package_rentals', to='saritasapp.user'),
        ),
        migrations.AddField(
            model_name='wardrobepackagerental',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_package_rentals', to='saritasapp.user'),
        ),
        migrations.AddField(
            model_name='wardrobepackagerental',
            name='damage_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wardrobepackagerental',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wardrobepackagerental',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagerentalitem',
            name='condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent - No visible wear'), ('good', 'Good - Minor wear'), ('fair', 'Fair - Some wear but functional'), ('poor', 'Poor - Significant wear/damage'), ('damaged', 'Damaged - Needs repair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='packagerentalitem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_rentals', to='saritasapp.inventory'),
        ),
        migrations.AlterField(
            model_name='packagerentalitem',
            name='package_rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_items', to='saritasapp.wardrobepackagerental'),
        ),
        migrations.AlterField(
            model_name='wardrobepackagerental',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_rentals', to='saritasapp.customerorder'),
        ),
        migrations.AlterField(
            model_name='wardrobepackagerental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rented', 'Rented'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='wardrobepackagerental',
            index=models.Index(fields=['status'], name='saritasapp__status_f6f097_idx'),
        ),
        migrations.AddIndex(
            model_name='wardrobepackagerental',
            index=models.Index(fields=['rental_start', 'rental_end'], name='saritasapp__rental__ea9b5d_idx'),
        ),
    ]
