# Generated by Django 4.0 on 2025-03-30 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0004_fittingappointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rental', 'verbose_name_plural': 'Rentals'},
        ),
        migrations.AddField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_end',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_start',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rented', 'Rented'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['rental_start', 'rental_end'], name='saritasapp__rental__8cd9c7_idx'),
        ),
    ]
