# Generated by Django 4.0 on 2025-04-20 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0005_alter_packagerentalitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wardrobepackagerental',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='wardrobepackagerental',
            name='saritasapp__status_f6f097_idx',
        ),
        migrations.RemoveIndex(
            model_name='wardrobepackagerental',
            name='saritasapp__rental__ea9b5d_idx',
        ),
        migrations.RenameField(
            model_name='wardrobepackagerental',
            old_name='rental_end',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='wardrobepackagerental',
            old_name='rejection_reason',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='customized_package',
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='damage_fee',
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='late_fee',
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='order',
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='rental_start',
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='wardrobepackagerental',
            name='return_condition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wardrobepackagerental',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_rentals', to='saritasapp.user'),
        ),
        migrations.AlterField(
            model_name='wardrobepackagerental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saritasapp.customer'),
        ),
        migrations.AlterField(
            model_name='wardrobepackagerental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
