# Generated by Django 4.0 on 2025-04-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0005_alter_rental_options_rental_created_at_rental_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rentals', to='saritasapp.user'),
        ),
        migrations.AddField(
            model_name='rental',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rented', 'Rented'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['status'], name='saritasapp__status_60560d_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['created_at'], name='saritasapp__created_2d09ca_idx'),
        ),
    ]
