# Generated by Django 4.2.20 on 2025-05-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0005_rental_picked_up_at_rental_pickup_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='pickup_verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='rental',
            name='pickup_status',
            field=models.CharField(blank=True, choices=[('awaiting', 'Awaiting Pickup'), ('picked_up', 'Picked Up'), ('no_show', 'No Show')], db_index=True, max_length=15, null=True),
        ),
    ]
