# Generated by Django 4.2.20 on 2025-04-29 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0005_alter_wardrobepackagerental_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wardrobepackageitem',
            options={'ordering': ['package', '-is_required'], 'verbose_name': 'Package Item', 'verbose_name_plural': 'Package Items'},
        ),
        migrations.AddField(
            model_name='wardrobepackageitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wardrobepackageitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
