# Generated by Django 4.0 on 2025-04-16 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0006_alter_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_price',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Flat reservation fee of ₱500.00 per item', max_digits=8, validators=[django.core.validators.MinValueValidator(500.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
