# Generated by Django 4.2.20 on 2025-05-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0006_rental_pickup_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rental',
            name='saritasapp__pickup__254ce2_idx',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='picked_up_at',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='pickup_status',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='pickup_verification_code',
        ),
    ]
