# Generated by Django 4.0 on 2025-04-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0006_alter_wardrobepackagerental_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='return_condition',
        ),
        migrations.RemoveField(
            model_name='wardrobepackagerental',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='wardrobepackagerental',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wardrobepackagerental',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wardrobepackagerental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
