# Generated by Django 4.2.20 on 2025-05-05 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0007_remove_rental_saritasapp__pickup__254ce2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='damage_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent - No issues'), ('good', 'Good - Minor wear'), ('fair', 'Fair - Needs cleaning/repair'), ('poor', 'Poor - Significant damage')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['return_condition'], name='saritasapp__return__0fff58_idx'),
        ),
    ]
