# Generated by Django 4.0 on 2025-04-17 01:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0008_notification_url_alter_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_price',
            field=models.DecimalField(decimal_places=2, default=500.0, editable=False, help_text='Flat reservation fee of ₱500.00 per item', max_digits=8, validators=[django.core.validators.MinValueValidator(500.0), django.core.validators.MaxValueValidator(500.0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=models.DateField(),
        ),
    ]
