# Generated by Django 4.0 on 2025-04-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0009_alter_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Renting', 'Renting'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rented', 'Rented'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=10),
        ),
    ]
