# Generated by Django 4.0 on 2025-04-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0010_alter_rental_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='inventory_decremented',
            field=models.BooleanField(default=False),
        ),
    ]
