# Generated by Django 4.0 on 2025-04-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0011_rental_inventory_decremented'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('rental_approved', 'Rental Approved'), ('rental_rejected', 'Rental Rejected'), ('rental_completed', 'Rental Completed'), ('reservation_approved', 'Reservation Approved'), ('reservation_rejected', 'Reservation Rejected'), ('reservation_completed', 'Reservation Completed'), ('payment_required', 'Payment Required'), ('payment_received', 'Payment Received'), ('rental_reminder', 'Rental Reminder'), ('return_reminder', 'Return Reminder'), ('system_alert', 'System Alert')], max_length=30),
        ),
    ]
