# Generated by Django 4.0 on 2025-04-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0012_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to='saritasapp.user'),
        ),
    ]
