# Generated by Django 4.0 on 2025-04-18 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saritasapp', '0013_reservation_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_phone', models.CharField(max_length=20)),
                ('provider_email', models.EmailField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='packageitem',
            name='acquired',
        ),
        migrations.RemoveField(
            model_name='packageitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='packageitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='packageitem',
            name='service_type',
        ),
        migrations.AddField(
            model_name='packageitem',
            name='external_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saritasapp.externalservice'),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saritasapp.service'),
        ),
    ]
