# Generated by Django 5.2 on 2025-04-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.CharField(blank=True, default='/collections', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
