# Generated by Django 5.2 on 2025-04-28 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_alter_herosection_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='button_text',
        ),
    ]
