# Generated by Django 4.2.20 on 2025-04-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_featuredcollectionssection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcollectionssection',
            name='title',
            field=models.CharField(default='Featured Collections', help_text='Title for this featured collection section', max_length=200),
        ),
    ]
