# Generated by Django 5.1.6 on 2025-04-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_featuredcollectionssection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcollectionssection',
            name='title',
        ),
    ]
